### ISSUE TITLE
Error when mentionning conflict between tlp and power-profile-daemon

### ISSUE THREAD

**Issue by integrated-circuit** [FrameworkComputer/linux-docs#1]
When talking about conflict between tlp and power-profile daemon in "ehancing battery life in linux", you ask to mask or remove power-profile. It isn't needed anymore as for tlp 1.5, which takes care of the issue by himself.

![Screenshot_20230502-151350_Brave.jpg](https://user-images.githubusercontent.com/68387582/235677773-7468d1d0-72c6-4799-a505-2a2d25e21db2.jpg)

![Screenshot_20230502-151331_Brave.jpg](https://user-images.githubusercontent.com/68387582/235677774-c1da63c8-1232-4de6-b27d-5d373976252d.jpg)

**Comment by ctsdownloads** [comment]
Interesting, looks like this may affect Ubuntu and Arch. I'll test this on a clean install, make sure it does what the TLP docs indicate. Then I'll update the docs once confirmed.

**Comment by ctsdownloads** [comment]
May be a few days before I have time to be absolutely sure power-profile behaves. TLP appears to absolutely be correct, but I do not trust power-profile to play nicely. Going to let this roll through some various updates first to make sure this remains correct, then I will update the docs. Great feedback! :)

**Comment by integrated-circuit** [comment]
No problem! Good luck with the investigation.

**Comment by ctsdownloads** [comment]
Confirmed on Ubuntu 22.04 and 23.04, install TLP 1.5.0 from the official Ubuntu repos, enable and start service, _reboot_ - power-profile remains active. 

So their docs are off on this one for Ubuntu it would appear. 
![tlp-power](https://github.com/FrameworkComputer/linux-docs/assets/18758065/514b2060-b477-40aa-b590-171d7df22ef2)
