### ISSUE TITLE
linux-oem-22.04d testing Framework Laptop 13

### ISSUE THREAD

**Issue by ctsdownloads** [FrameworkComputer/linux-docs#18]
Boots to black screen Framework Laptop 13 (AMD Ryzen™ 7040 Series)

Log to follow, will be tracking here.  Ubuntu 22.04.3, OEM D, 6.5.0.1009.11 boots to a black screen, blinking cursor - has AMDGPU feels. Will post logs shortly.

- steps to repro:

- AMD Ryzen™ 7040 Series laptop, Ubuntu 22.04.3, **OLD BIOS** (as this may come up, testing current next)
- Run the following:

```
sudo apt-get install linux-oem-22.04d -y
```

REBOOT

```
latest_oem_kernel=$(ls /boot/vmlinuz-* | grep '6.5.0-10..-oem' | sort -V | tail -n1 | awk -F'/' '{print $NF}' | sed 's/vmlinuz-//') && sudo sed -i.bak '/^GRUB_DEFAULT=/c\GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux '"$latest_oem_kernel"'"' /etc/default/grub && sudo update-grub && sudo apt install zenity && mkdir -p ~/.config/autostart && [ ! -f ~/.config/autostart/kernel_check.desktop ] && echo -e "[Desktop Entry]\nType=Application\nExec=bash -c \"latest_oem_kernel=\$(ls /boot/vmlinuz-* | grep '6.5.0-10..-oem' | sort -V | tail -n1 | awk -F'/' '{print \\\$NF}' | sed 's/vmlinuz-//') && current_grub_kernel=\$(grep '^GRUB_DEFAULT=' /etc/default/grub | sed -e 's/GRUB_DEFAULT=\\\"Advanced options for Ubuntu>Ubuntu, with Linux //g' -e 's/\\\"//g') && [ \\\"\\\${latest_oem_kernel}\\\" != \\\"\\\${current_grub_kernel}\\\" ] && zenity --text-info --html --width=300 --height=200 --title=\\\"Kernel Update Notification\\\" --filename=<(echo -e \\\"A newer OEM D kernel is available than what is set in GRUB. <a href='https://github.com/FrameworkComputer/linux-docs/blob/main/22.04-OEM-D.md'>Click here</a> to learn more.\\\")\"\nHidden=false\nNoDisplay=false\nX-GNOME-Autostart-enabled=true\nName[en_US]=Kernel check\nName=Kernel check\nComment[en_US]=\nComment=" > ~/.config/autostart/kernel_check.desktop
``` 

REBOOT

**Comment by ctsdownloads** [comment]
Loell, please recreate this on your 11th and 12th gen Framework Laptop 13s - post the results below.

**Comment by ctsdownloads** [comment]
Adding @loell  - just comment your findings here, include your `uname -r` after you've run everything.

**Comment by ctsdownloads** [comment]
@loell Fixed a typo, should be sudo apt-get install linux-oem-22.04d -y

**Comment by ctsdownloads** [comment]
@loell Good news, the issue I saw on BIOS 3.02 AMD was because of the BIOS. On 3.03, it's looking very good.
OEM D, 6.5.0.1009.11 boots perfectly on Framework Laptop 13 (AMD Ryzen™ 7040 Series) - will work on additional testing of this kernel on the 13 inch 7040 next week.

So we'll have you run through this process and then post your boot results. 


> Boots to black screen Framework Laptop 13 (AMD Ryzen™ 7040 Series)
> 
> Log to follow, will be tracking here. Ubuntu 22.04.3, OEM D, 6.5.0.1009.11 boots to a black screen, blinking cursor - has AMDGPU feels. Will post logs shortly.
> 
> * steps to repro:
> * AMD Ryzen™ 7040 Series laptop, Ubuntu 22.04.3, **OLD BIOS** (as this may come up, testing current next)
> * Run the following:
> 
> ```
> sudo apt-get install linux-oem-22.04d -y
> ```
> 
> REBOOT
> 
> ```
> latest_oem_kernel=$(ls /boot/vmlinuz-* | grep '6.5.0-10..-oem' | sort -V | tail -n1 | awk -F'/' '{print $NF}' | sed 's/vmlinuz-//') && sudo sed -i.bak '/^GRUB_DEFAULT=/c\GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux '"$latest_oem_kernel"'"' /etc/default/grub && sudo update-grub && sudo apt install zenity && mkdir -p ~/.config/autostart && [ ! -f ~/.config/autostart/kernel_check.desktop ] && echo -e "[Desktop Entry]\nType=Application\nExec=bash -c \"latest_oem_kernel=\$(ls /boot/vmlinuz-* | grep '6.5.0-10..-oem' | sort -V | tail -n1 | awk -F'/' '{print \\\$NF}' | sed 's/vmlinuz-//') && current_grub_kernel=\$(grep '^GRUB_DEFAULT=' /etc/default/grub | sed -e 's/GRUB_DEFAULT=\\\"Advanced options for Ubuntu>Ubuntu, with Linux //g' -e 's/\\\"//g') && [ \\\"\\\${latest_oem_kernel}\\\" != \\\"\\\${current_grub_kernel}\\\" ] && zenity --text-info --html --width=300 --height=200 --title=\\\"Kernel Update Notification\\\" --filename=<(echo -e \\\"A newer OEM D kernel is available than what is set in GRUB. <a href='https://github.com/FrameworkComputer/linux-docs/blob/main/22.04-OEM-D.md'>Click here</a> to learn more.\\\")\"\nHidden=false\nNoDisplay=false\nX-GNOME-Autostart-enabled=true\nName[en_US]=Kernel check\nName=Kernel check\nComment[en_US]=\nComment=" > ~/.config/autostart/kernel_check.desktop
> ```
> 
> REBOOT

**Comment by loell** [comment]
Tested with kernel **6.1.0-1027-oem** for both 11th and 12th gen for Ubuntu 22.04.3 oem kernel, connectivity for both wifi/bluetooth looks fine, designated media keys looks to be working, sound as well. Generally working with my brief testing.

**Comment by ctsdownloads** [comment]
@loell Appreciate this with 6.1.0-1027-oem. Can you also try [with 6.5.0.1009.11](https://packages.ubuntu.com/jammy/linux-oem-22.04d) (OEM D)

Namely, [the steps here](https://github.com/FrameworkComputer/linux-docs/issues/18#issuecomment-1857187464) should produce the correct result.

**Comment by loell** [comment]
Installed latest 6.5.0-1009-oem, at first boot it did have wifi and Bluetooth issue, have captured dmesg if needed, but subsequent reboots seems to resolve it. so far looking stable for now, will observe if wireless has issues with dropping from the network.

**Comment by ctsdownloads** [comment]
Closing this out. Testing on all fronts looks good. @loell if you see wifi drop off again, or if I do, we can re-open this.
