### ISSUE TITLE
Missing instructions for enabling fingerprint sensor

### ISSUE THREAD

**Issue by hewfish** [FrameworkComputer/linux-docs#2]
The Linux Instructions don't include anything for the fingerprint reader. These simple steps can be used to enable it. You just then need to enroll a fingerprint

sudo apt install libpam-fprintd

fprintd-enroll (then scan fingerprint)

sudo pam-auth-update (then select fingerprint authentication and enable it)

These steps should be added to the steps to enable fingerprint reader.

**Comment by ctsdownloads** [comment]
This has been resolved on Fedora 38 and Ubuntu 22.04.
https://guides.frame.work/Guide/Fedora+38+Installation+on+the+Framework+Laptop+13/165#s1341
https://guides.frame.work/Guide/Ubuntu+22.04+LTS+Installation+on+the+Framework+Laptop+13/109?lang=en#s1782
