### ISSUE TITLE
Ubuntu 22.04 OEM-C kernel update breaks brightness keys

### ISSUE THREAD

**Issue by graue** [FrameworkComputer/linux-docs#20]
Hello,

On a 13th-gen Intel Framework laptop running Ubuntu 22.04, the brightness keys do not work unless the `GRUB_CMDLINE_LINUX_DEFAULT` variable in `/etc/default/grub` contains the parameter `module_blacklist=hid_sensor_hub`.

Therefore, step 2 of Framework's [setup instructions](https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu22.04LTS-Manual-Setup-13thGen.md) includes a command that adds that parameter to that file (and runs `sudo update-grub`).

However, the [suggested commands to run to upgrade the OEM-C kernel](https://github.com/FrameworkComputer/linux-docs/blob/main/22.04-OEM-C.md) overwrite that value, causing the brightness keys to stop working. This caused a lot of confusion for me and substantial back-and-forth with your support team before finding the issue.

I recommend modifying the commands given in 22.04-OEM-C.md so that they don't overwrite that value and break the brightness key functionality.

**Comment by ctsdownloads** [comment]
@graue Ah, good catch! Yes, the code needs to be updated as not to beat up the existing parameters. I will put this into the queue for next week.

**Comment by ctsdownloads** [comment]
```
latest_oem_kernel=$(ls /boot/vmlinuz-* | awk -F"-" '{split($0, a, "-"); version=a[3]; if (version>max) {max=version; kernel=a[2] "-" a[3] "-" a[4]}} END{print kernel}') && sudo sed -i.bak '/^GRUB_DEFAULT=/c\GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux '"$latest_oem_kernel"'"' /etc/default/grub && sudo update-grub
```

This new script totally omits the step that explicitly sets GRUB_CMDLINE_LINUX_DEFAULT to quiet splash. 

**This step is removed:** _sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/g' /etc/default/grub_
