### ISSUE TITLE
Zenity no longer builds with the HTML support required by the kernel_check user session autostart script

### ISSUE THREAD

**Issue by brlin-tw** [FrameworkComputer/linux-docs#25]
Note that since Zenity 3.44.0-2 version the Debian (and thus, Ubuntu >=23.10) build of Zenity no longer builds with HTML support due to the "heavy" Webkit dependency concerns:

```
zenity (3.44.0-2) experimental; urgency=medium

   ...stripped...

  * d/control.in, d/rules: Disable WebKit integration (--html option).
    This adds several "heavy" dependencies, notably WebKit itself, but
    also video and spellchecking among others, which are undesired for
    a simple interactive dialog.
    The WebKit feature is disabled by default upstream, and several
    major distributions (including at least the Fedora/Red Hat family,
    Arch and openSUSE) don't enable it in their packaging, so portable
    software cannot rely on this option being available. According to
    codesearch.debian.net, none of the packages with a dependency on
    zenity use the --html option.
    The beginning of the Debian 13 cycle seems a good time to make this
    sort of potentially disruptive change; most likely nobody will notice
    this feature going away, but if we get bug reports, we can consider
    other options such as having a zenity-minimal package without HTML
    support, or having a zenity-full package with it.
    (Closes: #777608, #942362)

    ...stripped...

```

As such the user session autostart mechanism to suggest the user updating the GRUB default entry no longer works as the `--html` Zenity command-line option is no longer available:

```
$ zenity --text-info --html
This option is not available. Please see --help for all possible usages.
```

A possible workaround might be implementing the check mechanism using:

* The plain `--info` dialog, while using other mechanisms to open the webpage containing the next step instructions  

  ![Screenshot of using the --info dialog while achieving the similar effect](https://github.com/FrameworkComputer/linux-docs/assets/13408130/f01161ca-2aae-456e-ae8c-e6a0fa19afd3 "Screenshot of using the --info dialog while achieving the similar effect")
* Desktop notifications, though it seems that options based on this method are more limited/unpredictable.

**Comment by ctsdownloads** [comment]
Appreciate the heads up, but this won't be a thing for anything not LTS. As it's not affecting Ubuntu 22.04.4,  this is not applicable to 23.10 as we do not test against 23.10. We do not test against or use the OEM kernel on non-LTS releases.

We will be circling through to this in 24.04 as we put our docs together. Thanks for the report as this may affect 24.04.
