### ISSUE TITLE
Script for getting last version is wrong

### ISSUE THREAD

**Issue by sergejomon** [FrameworkComputer/linux-docs#27]

**Comment by sergejomon** [comment]
When listing available boot option in /boot I get the following result

`/boot/vmlinuz-6.1.0-1036-oem  /boot/vmlinuz-6.5.0-1019-oem  /boot/vmlinuz-6.5.0-27-generic`

The given script doesn't return vmlinuz-6.5.0-1019-oem as it should but vmlinuz-6.1.0-1036-oem
`
 $(ls /boot/vmlinuz-* | awk -F"-" '{split($0, a, "-"); version=a[3]; if (version>max) {max=version; kernel=a[2] "-" a[3] "-" a[4]}} END{print kernel}')`

**Comment by ctsdownloads** [comment]
Will repro today. On the surface, it looks like the issue was changing from OEM C to OEM D, which may not have taken correctly on your system.

**Comment by ctsdownloads** [comment]
Tested 6 times, was unable to replicate any issues whatsoever.
