### ISSUE TITLE
Command to enable fractional scaling does not activate it in the login screen - possible alternative

### ISSUE THREAD

**Issue by JebKerman91** [FrameworkComputer/linux-docs#28]
As per the title, the suggested command to enable fractional scaling
`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
 works, but not in the login screen.

Following this [the suggested way](https://wiki.archlinux.org/title/GDM#Setup_default_monitor_settings) to apply the monitor configuration to the display manager in general does not work:
`# cp ~/.config/monitors.xml /var/lib/gdm/.config/`

The suggested command at the end of [this thread](https://discussion.fedoraproject.org/t/too-high-resolution-on-login-screen/83445/6?replies_to_post_number=6) does however seem to do the trick and may be a useful addition to the docs:
`sudo -u gdm dbus-launch gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

**Comment by ctsdownloads** [comment]
Interesting idea, appreciate the feedback. I'll consider this in the near future. 

For now, using the existing command  provides fractional scaling once logged in. But I will investigate adding the other option in the near future.

**Comment by Vaarlion** [comment]
I can agree that this command is to keep in mind.
I've use it, and converted it using ansible a couple years ago for the framework 11.
https://gist.github.com/Vaarlion/1a71f11238ae06bc95565251204b1304#file-framework-setup-yml-L22

It haven't failed since
