### ISSUE TITLE
Following Framework 13 13th Gen brightness key documentation break them ?

### ISSUE THREAD

**Issue by Vaarlion** [FrameworkComputer/linux-docs#29]
I'm confused about this config in the documentations:

https://github.com/FrameworkComputer/linux-docs/blob/main/Fedora40-13thGen.md#enable-brightness-keys
https://github.com/FrameworkComputer/linux-docs/blob/main/Fedora39-13thGen.md#enable-brightness-keys

I just got a new 13th gen framework, and the brightness keys worked out of the box.
Running the command `sudo grubby --update-kernel=ALL --args="module_blacklist=hid_sensor_hub"`  and rebooting broke the brightness key.
Running the command `sudo grubby --update-kernel=ALL --remove-args="module_blacklist=hid_sensor_hub"` and rebooting brought that functionality back.

Is this a relica ? A typo ? Did i do something wrong ?

**Comment by JohnAZoidberg** [comment]
If it worked out of the box, why did you do anything? If it works, just enjoy it :)
Just to confirm, we are talking about the function of the keys also labeled as F7 and F8?

**Comment by Vaarlion** [comment]
> we are talking about the function of the keys also labeled as F7 and F8, which adjust the display brightness?

Yes those :)

> If it worked out of the box, why did you do anything?

RTFM, there is an official guide to setup the framework for fedora, i follow it. when i see something odd but reversible, i do it, learn from it, and if it is in fact wrong, i make an issue to have it fix for people who don't have the time to learn how to do this and just want to copy past from the guide :)

**Comment by ctsdownloads** [comment]
@Vaarlion confirmed this is no longer needed, F40 guides have been adjusted. F39 guides will be vetted later on. But as I did correct the F40 guides, closing this out.
