### ISSUE TITLE
FW16 Slow Resume from Standby on Ubuntu 24.04 and Debian Trixie

### ISSUE THREAD

**Issue by linux4life798** [FrameworkComputer/linux-docs#33]
# Ubuntu/24.04 on Framework 16 Slow Wake

It takes about 37 seconds from wake signal (keyboard or power button) to when the display finally wakes up.
I have attached the kernel messages from 4 independent standby and resume test cycles.

Procedure:

* Configure power button as Standby trigger.
* Clear kernel messages, `sudo dmesg -c`.
* Watch the kernel messages, `sudo dmesg -w`.
* Enter sleep by pushing the power button.
* Wait about 30 seconds.
* Push a key on the keyboard and start on a stopwatch simultaneously.
* Stop the stopwatch when the display finally wakes up.

Info:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

$ uname -a
Linux craigwork-ubuntu 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Kernel Messages:

[ubuntu-noble-slow-resume-1.txt](https://github.com/FrameworkComputer/linux-docs/files/15345575/ubuntu-noble-slow-resume-1.txt)
[ubuntu-noble-slow-resume-2.txt](https://github.com/FrameworkComputer/linux-docs/files/15345576/ubuntu-noble-slow-resume-2.txt)
[ubuntu-noble-slow-resume-3.txt](https://github.com/FrameworkComputer/linux-docs/files/15345577/ubuntu-noble-slow-resume-3.txt)
[ubuntu-noble-slow-resume-4.txt](https://github.com/FrameworkComputer/linux-docs/files/15345578/ubuntu-noble-slow-resume-4.txt)

**Comment by linux4life798** [comment]
# Debian/Trixie on Framework 16 Slow Wake

It also takes about 37 seconds from wake signal (keyboard or power button) to when the display finally wakes with Debian Trixie.
I have attached the kernel messages from 4 independent standby and resume test cycles.

Procedure:

* Configure power button as Standby trigger.
* Clear kernel messages, `sudo dmesg -c`.
* Watch the kernel messages, `sudo dmesg -w`.
* Enter sleep by pushing the power button.
* Wait about 30 seconds.
* Push a key on the keyboard and start on a stopwatch simultaneously.
* Stop the stopwatch when the display finally wakes up.

Info:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie

$ uname -a
Linux craigwork 6.7.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1 (2024-04-24) x86_64 GNU/Linux
```

Kernel Messages:
[debian-trixie-slow-resume-1.txt](https://github.com/FrameworkComputer/linux-docs/files/15344891/debian-trixie-slow-resume-1.txt)
[debian-trixie-slow-resume-2.txt](https://github.com/FrameworkComputer/linux-docs/files/15344892/debian-trixie-slow-resume-2.txt)
[debian-trixie-slow-resume-pressed-ctrl-many-times-3.txt](https://github.com/FrameworkComputer/linux-docs/files/15344894/debian-trixie-slow-resume-pressed-ctrl-many-times-3.txt)
[debian-trixie-slow-resume-4.txt](https://github.com/FrameworkComputer/linux-docs/files/15344893/debian-trixie-slow-resume-4.txt)

**Comment by ctsdownloads** [comment]
Debian Trixie is not something we test against and this is for Ubuntu specifically, so there are differences. 
That said, if you are experiencing slow to  wake on Ubuntu 24.04, fully update and on BIOS 3.03, please open a support ticket as there may be other factors. Also worth running this with the support ticket as well. https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py
