### ISSUE TITLE
Ryzen 7040 - Ubuntu default kernel or not?

### ISSUE THREAD

**Issue by danwritecode** [FrameworkComputer/linux-docs#37]
Hey all, there are conflicting messages in the email vs the docs.\

Email:
![image](https://github.com/user-attachments/assets/1376a856-5b36-4b42-ab3c-c23cb01aa12b)
 
However here it states that you SHOULD be using the default kernel:
https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu24.04LTS-Setup-amd-fw13.md

Also, at that link, the instructions are a bit confusing. There is an old screenshot there presumably for when you did need to do something with the kernel, but the contents from that screenshot do not match the contents in the code block that now exists.

When I see something say "it's critical you don't use the default kernel" and then see conflicting information, I really want to make sure I get things right before I spend time setting up my laptop.

**Comment by ctsdownloads** [comment]
Hi @danwritecode,

Appreciate the call out. The email is outdated and will be corrected. The steps provided here are current.
https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu24.04LTS-Setup-amd-fw13.md 

Thank you, we'll get the email updated.

**Comment by danwritecode** [comment]
thanks @ctsdownloads you guys are awesome!
