### ISSUE TITLE
Unclear kernel OEM/Default?

### ISSUE THREAD

**Issue by xgpt** [FrameworkComputer/linux-docs#39]
In regards to : https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu24.04LTS-Setup-amd-fw13.md

"We are NOT recommending an OEM kernel at this time, this may change in the future. Default kernel is where you need to be." is unclear to me. I might just be dense here, but I'm not sure what action to take based on this documentation. How do I switch to a "Default Kernel" from "OEM"? Is there a command I should run? As there are other commands in this file, I would appreciate a bit of hand holding on this issue from the document.

I'm sure I'm not as confused as a newer Linux user might be either. Switching kernels is pretty easy in 2024, at least compared to 2007 when I started, but since this is specific to a specific version of a single Distro, I think it would be appropriate to link to a guide or embed one here that says something like

```bash
sudo apt update
sudo apt install {some-specific-officially-supported-Default}-Linux-Kernel-package
{any GRUB update commands needed}
...etc etc ...
```

**Comment by xgpt** [comment]
I was brought here after reading the official welcome email that outlined installing a new OS to my New framework. I'm mostly confused because I don't remember fiddling with the kernel at all and it all seemed to run fine, but I'm very happy to switch to something more-officially-supported by Framework if that's what is recommended. Also I've noticed that documentation will continue to recommend switching to specific kernels, but won't stop recommending that if whatever-quirk-of-the-month gets fixed in the more mainline kernel and no swap is actually needed. Documentation often lags kernel development, so I made this issue just to ask for clarification on what kernel is needed in September of 2024! 

Thanks! Sorry if this is coming off as pedantic

**Comment by ctsdownloads** [comment]
Appreciate the feedback. The new customer welcome email should be updated now. 

One of the challenges with Ubuntu is in some instances, we may or may not rely on OEM kernels, hardware and LTS release depending. So each guide has the correct instruction set as needed. As LTS releases age, the kernel ages with it and doesn't see the bleeding edge releases seen on other distros. I does and will vary and change. 

Good news is, right now all you need to do is install, update and run the distro. No changes to kernel settings are needed for Framework Laptop 13/16 AMD Ryzen 7040 Series.
