### ISSUE TITLE
Ubuntu Framework 13: gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']" - blurred screen

### ISSUE THREAD

**Issue by MaieulChevalier** [FrameworkComputer/linux-docs#4]
For Ubuntu 22 on framework 13, `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"` creates a blurred screen that many people don't like.

Shouldn't the [doc](https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu22.04LTS-Manual-Setup-13thGen.md) propose this script as optional?

I had a hard time understanding that this caused the blurring and even wondered if I was sick or something :sweat_smile:

**Comment by maieulChevalier** [comment]
Just a heads-up to say that I accidentally found that I could change the scaling factor with gnome-tweaks, without any blurring issues. This might be an interesting path for others to consider as well. Could be added to the doc, what do you think?
