### ISSUE TITLE
external_video.sh script permissions

### ISSUE THREAD

**Issue by playday3008** [FrameworkComputer/linux-docs#44]
Add this to documentation:
```bash
sudo chmod +x /usr/local/bin/external_video.sh
```

or udev rule will fail

**Comment by ctsdownloads** [comment]
Correct and great catch - permissions matter. Will add this shortly. 

Self: need to adjust this for Fedora and Ubuntu guides. Not closing this until the corrected is added to each guide.

**Comment by ctsdownloads** [comment]
Fixed the docs for F41, F40 and Ubuntu 24.04
