### ISSUE TITLE
`latest_oem_kernel` value is not correct for Ubuntu 22 Manual Setup 13th Gen

### ISSUE THREAD

**Issue by ltirrell** [FrameworkComputer/linux-docs#8]
In the [Ubuntu22 Manual Setup Guide](https://github.com/FrameworkComputer/linux-docs/blob/main/Ubuntu22.04LTS-Manual-Setup-13thGen.md#indentify-your-oem-c-kernel), the command to identify the latest kernel gives an incorrect result (also a typo in the section header, `s/Indentify/Identify/`)

The following command gives `5.17.0-1035-oem`, instead of `6.1.0-1021-oem`:
```
ls /boot/vmlinuz-* | awk -F"-" '{split($0, a, "-"); version=a[3]; if (version>max) {max=version; kernel=a[2] "-" a[3] "-" a[4]}} END{print kernel}'
```

Here is what is in the /boot/ directory on my machine:
```
$ ls -lrth /boot/vmlinuz-*
-rw------- 1 root root 11M Jul 12 02:49 /boot/vmlinuz-5.17.0-1035-oem
-rw------- 1 root root 14M Aug 18 02:40 /boot/vmlinuz-6.2.0-32-generic
-rw------- 1 root root 12M Aug 22 04:59 /boot/vmlinuz-6.1.0-1021-oem
```

Not sure what the best solution for this is

**Comment by ctsdownloads** [comment]
If you are on Ubuntu **22.04.3**, and you have the OEM C kernel installed, this will result in the following (just retested it):

`ls /boot/vmlinuz-* | awk -F"-" '{split($0, a, "-"); version=a[3]; if (version>max) {max=version; kernel=a[2] "-" a[3] "-" a[4]}} END{print kernel}'`

6.1.0-1024-oem

I am unable to replicate your error.

I'm unclear as to what you're running, but it sounds like you're on something else.
As you can see here, that kernel isn't listed at all: https://packages.ubuntu.com/search?keywords=linux-oem-22.04

You should have linux-oem-22.04c installed on Ubuntu 22.04.3.
